### ISSUE TITLE
the gpu memory is out of, what model are you using?

### ISSUE THREAD

**Issue by qiuxiaolong857** [MrChenFeng/SSR_BMVC2022#1]
I'd like to ask a question,The size of the graphics device you are using to run the Clothing1M and WebVision data sets?I reproduced the results and found that the memory required for these two data sets was large

**Comment by MrChenFeng** [comment]
Hi, I'm experimenting with Nvidia 3090Ti. If you don't have enough GPU memory, try to reduce the batchsize.
