### ISSUE TITLE
Question about the feature consistency regularization.

### ISSUE THREAD

**Issue by chenmc1996** [MrChenFeng/SSR_BMVC2022#2]
I see that the method encourages augmentation consistency between the projection head and prediction head for the non-parametric KNN. 
The design is unusual to me. I thought consistency loss should put between the same part of network's outputs, e.g., after the same projection head or after the same prediction head. 
Could the authors share the behind ideas or reasons of such design? 
Thanks!

**Comment by MrChenFeng** [comment]
Hi, 
We actually followed the non-symmetric structure in recent self-supervised learning works, such as BYOL/SimSiam.

Best,
Chen

**Comment by chenmc1996** [comment]
I'll have to look into that.much appreciated!
