### ISSUE TITLE
questions about the weighted KNN

### ISSUE THREAD

**Issue by qyjiang19** [MrChenFeng/SSR_BMVC2022#4]
In line 43-45 of utils/funcs.py, why reassign sim_weight with same values and discard the original weight information? It seems it's an ordinary KNN, not a weighted KNN?

**Comment by MrChenFeng** [comment]
Hi, we actually use normal KNN by default, the weighted-version is for comparison only. We finally abandon it for method simplicity.

**Comment by qyjiang19** [comment]
got it, thank you!
