### ISSUE TITLE
Noisy dataset path

### ISSUE THREAD

**Issue by ghoshsdeeep** [MrChenFeng/SSR_BMVC2022#5]
Hello
In order to reproduce the results for CIFAR 100 , what should be given in the argument --noisy_dataset_path ?

![Screenshot (116)](https://github.com/MrChenFeng/SSR_BMVC2022/assets/12712069/47ff108c-c19d-4545-8231-4727a20ba930)

**Comment by MrChenFeng** [comment]
Hi, 
following previous works, we didn't carry experiments on CIFAR100 involving open-set noise. For only reproduction, you can levae it alone. If you want to try open-set noise with CIFAR100, You can use any other dataset other than CIFAR100 for open-set noise source here, correspondingly modify the dataloader part.
Best,
Chen

**Comment by ghoshsdeeep** [comment]
Thank You Chen for the reply
so we can use CIFAR 100 as the original dataset and CIFAR10 as the noisy dataset?

**Comment by MrChenFeng** [comment]
Yes, but you have to modify the dataloader to ensure it is included as open-set noise as you expected.
