### ISSUE TITLE
Issues trying to re-run the code

### ISSUE THREAD

**Issue by AlejandraM97** [MrChenFeng/SSR_BMVC2022#6]
Hi!

Hope you are well, I've seen your paper, and it is pretty interesting... I'm trying to re-run it... nevertheless, this problem shows

Epoch [0/300] selection: theta_s:1.0 TP: 4561 FP:150 TN:9754 FN:35535
Epoch [0/300] relabelling:  correct: 0 original: 0 total: 0
  0%|                                                                            | 0/390 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data/arumota/SSR_BMVC2022/main_cifar.py", line 62, in train
    [inputs_x1, inputs_x2], labels_x, _, index = labeled_train_iter.next()
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/arumota/SSR_BMVC2022/main_cifar.py", line 316, in <module>
    main()
  File "/data/arumota/SSR_BMVC2022/main_cifar.py", line 287, in main
    train(labeled_loader, modified_label, all_loader, encoder, classifier, proj_head, pred_head, optimizer, i, args)
  File "/data/arumota/SSR_BMVC2022/main_cifar.py", line 65, in train
    [inputs_x1, inputs_x2], labels_x, _, index = labeled_train_iter.next()
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'

I know it is because of the dataset... how do u process this data?

**Comment by MrChenFeng** [comment]
.next() is not supported by new torch, I have updated the code.
